package lnu.study.entity.enums;

public enum UserState {
    BASIC_STATE,
    WAIT_FOR_EMAIL_STATE,
    EMAIL_CONFIRMED_STATE,
    AWAITING_FILE_FOR_CONVERSION,
    AWAITING_TARGET_FORMAT_SELECTION,
    ARCHIVING_FILES;
}
